[package]
name        = "ucg"
version     = "0.0.1"
authors     = ["Jeremy Wall <jeremy@marzhillstudios.com>"]
description = "Runs a command on user specified triggers."
repository  = "https://github.com/zaphar/ucg"
readme      = "README.md"
keywords    = ["compiler", "config"]
license     = "Apache-2.0"

[dependencies.nom]
version        = "^3.2"

[dependencies]
nom_locate  = "^0.1.1"
clap        = "~2.26.0"
serde_json = "~1.0.9"

[lib]
name = "ucglib"
path = "src/lib.rs"

[[bin]]
name = "ucg"
path = "src/main.rs"
